.PHONY: clean All

All:
	@echo "----------Building project:[ TOH_Project - Debug ]----------"
	@cd "TOH_Project" && "$(MAKE)" -f  "TOH_Project.mk"
clean:
	@echo "----------Cleaning project:[ TOH_Project - Debug ]----------"
	@cd "TOH_Project" && "$(MAKE)" -f  "TOH_Project.mk" clean
